#!/bin/bash
EXTENSION_NAME="eZSVN"
EXTENSION_IDENTIFIER="ezsvn"
EXTENSION_SUMMARY="eZ SVN Package"
EXTENSION_LICENSE="GPL"
EXTENSION_VERSION="1.0"
EXTENSION_PUBLISH_VERSION="3.5"
EXTENSION_ARCHIVE_NAME="ezsvn"
EXTENSION_PHP_VERSION="4.3.2"

EXTENSION_FILTER_FILES="INSTALL.txt README.txt"
